export const createFormJson = {
  modelName: 'Category',
  controllerName: 'CategoryController',
  controls: [
    {
      name: 'type',
      label: 'Type',
      value: null,
      colLength: 3,
      placeholder: 'Select Type',
      type: 'dropdown',
      emitChange: false,
      readOnly: false,
      validators: { required: false },
      minFractionDigits: 2,
      steps: 1,
      dateFormat: 'dd/mm/yy',
      errors: [],
      options: [],
      database: {
        nullable: false,
        defaultFieldAllowed: false,
        defaultFieldValue: null,
        type: 'string',
        enumValues: [],
        foreignKeyEnabled: false,
        foreignKeyColumns: null,
        foreignKeyTable: null,
      },
      filter: false,
      filterBy: '',
      showClear: false,
    },
    {
      name: 'zone',
      label: 'Zone',
      value: null,
      colLength: 3,
      placeholder: 'Select Zone',
      type: 'dropdown',
      emitChange: false,
      readOnly: false,
      validators: { required: false },
      minFractionDigits: 2,
      steps: 1,
      dateFormat: 'dd/mm/yy',
      errors: [],
      options: [],
      database: {
        nullable: false,
        defaultFieldAllowed: false,
        defaultFieldValue: null,
        type: 'string',
        enumValues: [],
        foreignKeyEnabled: false,
        foreignKeyColumns: null,
        foreignKeyTable: null,
      },
      filter: false,
      filterBy: '',
      showClear: false,
    },
    {
      name: 'region',
      label: 'Region',
      value: null,
      colLength: 3,
      placeholder: 'Select Region',
      type: 'dropdown',
      emitChange: false,
      readOnly: false,
      validators: { required: false },
      minFractionDigits: 2,
      steps: 1,
      dateFormat: 'dd/mm/yy',
      errors: [],
      options: [],
      database: {
        nullable: false,
        defaultFieldAllowed: false,
        defaultFieldValue: null,
        type: 'string',
        enumValues: [],
        foreignKeyEnabled: false,
        foreignKeyColumns: null,
        foreignKeyTable: null,
      },
      filter: false,
      filterBy: '',
      showClear: false,
    },
    {
      name: 'team_type',
      label: 'Team Type',
      value: null,
      colLength: 3,
      placeholder: 'Select Team Type',
      type: 'dropdown',
      emitChange: false,
      readOnly: false,
      validators: { required: false },
      minFractionDigits: 2,
      steps: 1,
      dateFormat: 'dd/mm/yy',
      errors: [],
      options: [],
      database: {
        nullable: false,
        defaultFieldAllowed: false,
        defaultFieldValue: null,
        type: 'string',
        enumValues: [],
        foreignKeyEnabled: false,
        foreignKeyColumns: null,
        foreignKeyTable: null,
      },
      filter: false,
      filterBy: '',
      showClear: false,
    },
    {
      name: 'name',
      label: 'Person Name',
      value: null,
      colLength: 3,
      placeholder: 'Select Person Name',
      type: 'dropdown',
      emitChange: false,
      readOnly: false,
      validators: { required: false },
      minFractionDigits: 2,
      steps: 1,
      dateFormat: 'dd/mm/yy',
      errors: [],
      options: [],
      database: {
        nullable: false,
        defaultFieldAllowed: false,
        defaultFieldValue: null,
        type: 'string',
        enumValues: [],
        foreignKeyEnabled: false,
        foreignKeyColumns: null,
        foreignKeyTable: null,
      },
      filter: false,
      filterBy: '',
      showClear: false,
    },
    {
      name: 'cSelect_type',
      label: 'Center Type',
      value: null,
      placeholder: 'Select Center Type',
      type: 'dropdown',
      emitChange: false,
      readOnly: false,
      validators: { required: false },
      minFractionDigits: 2,
      steps: 1,
      colLength: 3,
      dateFormat: 'dd/mm/yy',
      errors: [],
      options: [],
      database: {
        nullable: false,
        defaultFieldAllowed: false,
        defaultFieldValue: null,
        type: 'string',
        enumValues: [],
        foreignKeyEnabled: false,
        foreignKeyColumns: null,
        foreignKeyTable: null,
      },
      filter: false,
      filterBy: '',
      showClear: false,
    },
    {
      name: 'cSelect_name',
      label: 'Center Name',
      value: null,
      placeholder: 'Select Center Name',
      type: 'dropdown',
      emitChange: false,
      readOnly: false,
      validators: { required: false },
      minFractionDigits: 2,
      steps: 1,
      dateFormat: 'dd/mm/yy',
      errors: [],
      options: [],
      database: {
        nullable: false,
        defaultFieldAllowed: false,
        defaultFieldValue: null,
        type: 'string',
        enumValues: [],
        foreignKeyEnabled: false,
        foreignKeyColumns: null,
        foreignKeyTable: null,
      },
      filter: false,
      filterBy: '',
      colLength: 3,
      showClear: false,
    },
  ],
};
